---
- hosts: localhost
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: jenkin-rg
      allocation_method: Static
      name: docvmpbip
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: jenkin-rg
      name: nicansi
      virtual_network: jenkins-vnet
      subnet: subnet1
      public_ip_name: docvmpbip
      security_group: nsg
  - name: Create a VM with resource group and vnet
    azure_rm_virtualmachine:
      resource_group: jenkin-rg
      name: docvm
      vm_size: Standard_DS1_v2
      managed_disk_type: Premium_LRS
      admin_username: vmadmin
      ssh_password_enabled: false
      ssh_public_keys:
      - path: /home/vmadmin/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMpX6D0J4mt+7hpwRbIftMD8b7CQreTaecMeKmtd2b/4oefiEaGdSiY7Row8wRelp7fpNEa/RR2g7V7QBA/iLtwNO8MX2a1OVNz6Du/pYbosfduFJetmtST390WmBQ5BrBT9ZPF/3sn0k4yDTkuRt9WPnaVk84RcErrWJyOMeRzd0r/YtfCQP6JH9Q0KfRzCpm5PoRUJjfNg8kfnIPXgoxbQ/8zQKWXzN1gxVRIWZ08vX3Qa6geRL1LVn+JJ8Qn3V6+y3oknJKhtDrghvBTj4oU4Au4ZYOcS+4LbnMjeEy401ylhn8AN3k9uzMe4ENZg/r6jdcQpZeDw+hQSNJhROCQdcy2aBQh2Z5Mfx1HrpIXe7+yDjkeANq4MOJoCOb+yqA07XpcJOVoTrqmkVI0jUnTCc03fTjCKg5L92g93ThTmkXBks1xWePtn8C6lsklG3x5RYH921kLr2zqUgBFUlDjHHBeleh4l7SUCyrr2bDE4oBgwL0vvkCF83DE9zh1LvhFuHNYXZyy0n4ozJN6Y78lEqit68Yf1UW5gxMyLCwyulCUQaLZdPifSpVVujDkfCuKHR7EaLAbj8gLllLK51xTsdywX7Ro9Ykp2jYNehhcD3W/3+sn0yJlyzzF4YF1ZoIJXI2KJrBu7kfOLAPox782ChTbvhhdkE/kEwgIJs4AQ== vmadmin@vm-build"
      network_interfaces: nicansi
      os_type: Linux
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 18.04-LTS
        version: latest
